/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([IDL.Text], [], []),
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([IDL.Text], [], []),
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };